config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
require 'redis'

class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  after_action :delete_indexed_values, only: [:create, :edit, :update, :destroy]
  after_action :dev_mode
  before_action :cleanup_mode

  # GET /todos
  # GET /todos.json
  def index
    @title = ENV['TITLE'] || "TODO Application (Dev)"

    redis = get_redis_connection

    todojson = redis.get "index"

    if todojson.blank?
      todoactiverecord = Todo.all
      #save in REDIS
      todojson = todoactiverecord.to_json
      redis.set "index",todojson
    end

    @todos = ActiveSupport::JSON.decode todojson


  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def delete_indexed_values
      redis = get_redis_connection
      redis.del("index")
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:description, :is_completed, :target_date)
    end

    def get_redis_connection

      u = ENV['REDIS_URL']

      if ENV['VCAP_SERVICES'].present?
        vcap = JSON.parse(ENV['VCAP_SERVICES'])["redis"]
        credentials = vcap.first["credentials"]
        u = credentials["uri"]
      end

      Redis.new(:url => u)

    end


  def cleanup_mode
    #also, delete the redis (flushall). We are doing this, just so
    #that there is a way to clear redis
    if params[:flushredis]
      redis = get_redis_connection
      redis.flushall
    end
  end

  def dev_mode

    #if in the query string you pass debug=true (or any value for debug, it will print the VCAP_APPLICATION)
    #mainly used to see multiple instance working and which particular instance the page got served.
    if params[:debug]
      @vcap_details = "VCAP details not available"
      @vcap_details = JSON.parse(ENV['VCAP_SERVICES']) if ENV['VCAP_SERVICES'].present?
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/todos.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todolist" %></title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">HP Helion Todo List</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">

          <%= yield %>
        </div>

      </div><!--/row-->

      <br> <br>
      <footer>
        <p>For more code, visit <a href="http://hdn.hpcloud.com">HP Helion Developer Network</a></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo, :html => { :class => "form-horizontal todo" } do |f| %>

    <% if @todo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_completed, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :is_completed %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :target_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :target_date, :class => 'form-control' %>
    </div>
  </div>

   <br>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  todos_path, :class => 'btn btn-default' %>
<% end %>

app/views/todos/edit.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todos/index.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=@title%></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:is_completed) %></th>
      <th><%= model_class.human_attribute_name(:target_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= link_to todo["id"], todo_path(todo["id"]) %></td>
        <td><%= todo["description"] %></td>
        <td><%= todo["is_completed"] %></td>
        <td><%= todo["target_date"] %></td>
        <td><%= todo["created_at"].to_datetime.strftime("%Y-%m-%d") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_todo_path(todo["id"]), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      todo_path(todo["id"]),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_todo_path,
            :class => 'btn btn-primary' %>

<div>
  <br>
  <%=@vcap_details%>
</div>

app/views/todos/new.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todos/show.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @todo.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_completed) %>:</strong></dt>
  <dd><%= @todo.is_completed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:target_date) %>:</strong></dt>
  <dd><%= @todo.target_date %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              todos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_todo_path(@todo), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              todo_path(@todo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>